pouria@ubuntu:~$ source env/cascade/bin/activate
bash: env/cascade/bin/activate: No such file or directory
pouria@ubuntu:~$ source cascade/env/bin/activate
(env) pouria@ubuntu:~$ cd cascade
(env) pouria@ubuntu:~/cascade$ deactivate
pouria@ubuntu:~/cascade$ cd ~/tutorial
pouria@ubuntu:~/tutorial$ python3 -m venv venv
pouria@ubuntu:~/tutorial$ source venv/bin/activate
(venv) pouria@ubuntu:~/tutorial$ pip install django
Collecting django
  Using cached Django-3.1-py3-none-any.whl (7.8 MB)
Collecting sqlparse>=0.2.2
  Using cached sqlparse-0.3.1-py2.py3-none-any.whl (40 kB)
Collecting pytz
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting asgiref~=3.2.10
  Using cached asgiref-3.2.10-py3-none-any.whl (19 kB)
Installing collected packages: sqlparse, pytz, asgiref, django
Successfully installed asgiref-3.2.10 django-3.1 pytz-2020.1 sqlparse-0.3.1
(venv) pouria@ubuntu:~/tutorial$ pip install djangorestframework
Collecting djangorestframework
  Using cached djangorestframework-3.11.1-py3-none-any.whl (911 kB)
Requirement already satisfied: django>=1.11 in ./venv/lib/python3.8/site-packages (from djangorestframework) (3.1)
Requirement already satisfied: pytz in ./venv/lib/python3.8/site-packages (from django>=1.11->djangorestframework) (2020.1)
Requirement already satisfied: sqlparse>=0.2.2 in ./venv/lib/python3.8/site-packages (from django>=1.11->djangorestframework) (0.3.1)
Requirement already satisfied: asgiref~=3.2.10 in ./venv/lib/python3.8/site-packages (from django>=1.11->djangorestframework) (3.2.10)
Installing collected packages: djangorestframework
Successfully installed djangorestframework-3.11.1
(venv) pouria@ubuntu:~/tutorial$ pip install pygments
Collecting pygments
  Using cached Pygments-2.6.1-py3-none-any.whl (914 kB)
Installing collected packages: pygments
Successfully installed pygments-2.6.1
(venv) pouria@ubuntu:~/tutorial$ django-admin startproject login
(venv) pouria@ubuntu:~/tutorial$ cd login
(venv) pouria@ubuntu:~/tutorial/login$ python manage.py startapp todos
(venv) pouria@ubuntu:~/tutorial/login$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK
(venv) pouria@ubuntu:~/tutorial/login$ python manage.py makemigrations todos
Migrations for 'todos':
  todos/migrations/0001_initial.py
    - Create model Todo
(venv) pouria@ubuntu:~/tutorial/login$ python manage.py migrate todos
Operations to perform:
  Apply all migrations: todos
Running migrations:
  Applying todos.0001_initial... OK
(venv) pouria@ubuntu:~/tutorial/login$ python manage.py createsuperuser
Username (leave blank to use 'pouria'): 
Email address: 123
Error: Enter a valid email address.
Email address: 123
Error: Enter a valid email address.
Email address: pouria@example.com
Password: 
Password (again): 
This password is too short. It must contain at least 8 characters.
This password is too common.
This password is entirely numeric.
Bypass password validation and create user anyway? [y/N]: y
Superuser created successfully.
(venv) pouria@ubuntu:~/tutorial/login$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 06:31:32
Django version 3.1, using settings 'login.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Error: That port is already in use.
(venv) pouria@ubuntu:~/tutorial/login$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 06:31:45
Django version 3.1, using settings 'login.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[23/Aug/2020 06:31:49] "GET / HTTP/1.1" 200 16351
[23/Aug/2020 06:31:49] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[23/Aug/2020 06:31:49] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[23/Aug/2020 06:31:49] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[23/Aug/2020 06:31:49] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[23/Aug/2020 06:32:20] "GET /admin/ HTTP/1.1" 302 0
[23/Aug/2020 06:32:20] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2194
[23/Aug/2020 06:32:20] "GET /static/admin/css/base.css HTTP/1.1" 200 16307
[23/Aug/2020 06:32:20] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 1789
[23/Aug/2020 06:32:20] "GET /static/admin/css/login.css HTTP/1.1" 200 1185
[23/Aug/2020 06:32:20] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18617
[23/Aug/2020 06:32:24] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
[23/Aug/2020 06:32:28] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[23/Aug/2020 06:32:28] "GET /admin/ HTTP/1.1" 200 3938
[23/Aug/2020 06:32:28] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[23/Aug/2020 06:32:28] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[23/Aug/2020 06:32:28] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[23/Aug/2020 06:33:15] "GET /admin/todos/todo/add/ HTTP/1.1" 200 6084
[23/Aug/2020 06:33:15] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[23/Aug/2020 06:33:15] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[23/Aug/2020 06:33:15] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[23/Aug/2020 06:33:15] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[23/Aug/2020 06:33:15] "GET /static/admin/css/forms.css HTTP/1.1" 200 8399
[23/Aug/2020 06:33:15] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[23/Aug/2020 06:33:15] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
[23/Aug/2020 06:33:15] "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[23/Aug/2020 06:33:15] "GET /admin/jsi18n/ HTTP/1.1" 200 3187
[23/Aug/2020 06:33:15] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[23/Aug/2020 06:33:15] "GET /static/admin/css/widgets.css HTTP/1.1" 200 10592
[23/Aug/2020 06:33:16] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
[23/Aug/2020 06:33:16] "GET /static/admin/js/core.js HTTP/1.1" 200 5418
[23/Aug/2020 06:33:16] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6078
[23/Aug/2020 06:33:16] "GET /static/admin/js/actions.js HTTP/1.1" 200 6783
[23/Aug/2020 06:33:16] "GET /static/admin/js/urlify.js HTTP/1.1" 200 8632
[23/Aug/2020 06:33:16] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[23/Aug/2020 06:33:16] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[23/Aug/2020 06:33:16] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "POST /admin/todos/todo/add/ HTTP/1.1" 302 0
[23/Aug/2020 06:34:11] "GET /admin/todos/todo/ HTTP/1.1" 200 6144
[23/Aug/2020 06:34:11] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6284
[23/Aug/2020 06:34:11] "GET /admin/jsi18n/ HTTP/1.1" 200 3187
[23/Aug/2020 06:34:11] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[23/Aug/2020 06:34:11] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[23/Aug/2020 06:34:11] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[23/Aug/2020 06:34:24] "GET /admin/todos/todo/add/ HTTP/1.1" 200 6084
[23/Aug/2020 06:34:24] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[23/Aug/2020 06:34:24] "GET /admin/jsi18n/ HTTP/1.1" 200 3187
[23/Aug/2020 06:34:24] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[23/Aug/2020 06:34:24] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[23/Aug/2020 06:34:24] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "POST /admin/todos/todo/add/ HTTP/1.1" 302 0
[23/Aug/2020 06:35:05] "GET /admin/todos/todo/add/ HTTP/1.1" 200 6306
[23/Aug/2020 06:35:05] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /admin/jsi18n/ HTTP/1.1" 200 3187
[23/Aug/2020 06:35:05] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[23/Aug/2020 06:35:05] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
[23/Aug/2020 06:36:24] "POST /admin/todos/todo/add/ HTTP/1.1" 302 0
[23/Aug/2020 06:36:24] "GET /admin/todos/todo/add/ HTTP/1.1" 200 6306
[23/Aug/2020 06:36:24] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[23/Aug/2020 06:36:24] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[23/Aug/2020 06:36:24] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[23/Aug/2020 06:36:24] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[23/Aug/2020 06:36:24] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[23/Aug/2020 06:36:24] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[23/Aug/2020 06:36:24] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[23/Aug/2020 06:36:24] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[23/Aug/2020 06:36:25] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[23/Aug/2020 06:36:25] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[23/Aug/2020 06:36:25] "GET /admin/jsi18n/ HTTP/1.1" 200 3187
[23/Aug/2020 06:36:25] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[23/Aug/2020 06:36:25] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[23/Aug/2020 06:36:25] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[23/Aug/2020 06:36:25] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[23/Aug/2020 06:36:25] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[23/Aug/2020 06:36:25] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[23/Aug/2020 06:36:25] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[23/Aug/2020 06:36:25] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[23/Aug/2020 06:36:25] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
[23/Aug/2020 06:36:52] "POST /admin/todos/todo/add/ HTTP/1.1" 302 0
[23/Aug/2020 06:36:52] "GET /admin/todos/todo/ HTTP/1.1" 200 6745
[23/Aug/2020 06:36:52] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[23/Aug/2020 06:36:52] "GET /admin/jsi18n/ HTTP/1.1" 200 3187
[23/Aug/2020 06:36:52] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
^C(venv) pouria@ubuntu:~/tutorial/login$ python manage.py startapp api
(venv) pouria@ubuntu:~/tutorial/login$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 07:02:16
Django version 3.1, using settings 'login.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Not Found: /
[23/Aug/2020 07:02:22] "GET / HTTP/1.1" 404 2027
[23/Aug/2020 07:03:04] "GET /api/v1 HTTP/1.1" 301 0
Internal Server Error: /api/v1/
Traceback (most recent call last):
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 723, in render
    template = loader.get_template(self.template)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
[23/Aug/2020 07:03:04] "GET /api/v1/ HTTP/1.1" 500 79609
/home/pouria/tutorial/login/api/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 07:06:05
Django version 3.1, using settings 'login.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /api/v1/
Traceback (most recent call last):
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 723, in render
    template = loader.get_template(self.template)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
[23/Aug/2020 07:06:10] "GET /api/v1/ HTTP/1.1" 500 79746
Internal Server Error: /api/v1/
Traceback (most recent call last):
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 723, in render
    template = loader.get_template(self.template)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
[23/Aug/2020 07:06:59] "GET /api/v1/ HTTP/1.1" 500 79609
^C(venv) pouria@ubuntu:~/tutorial/login$ python manage.py makemigrations
No changes detected
(venv) pouria@ubuntu:~/tutorial/login$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, todos
Running migrations:
  No migrations to apply.
(venv) pouria@ubuntu:~/tutorial/login$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 07:08:10
Django version 3.1, using settings 'login.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /api/v1/
Traceback (most recent call last):
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 723, in render
    template = loader.get_template(self.template)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
[23/Aug/2020 07:08:15] "GET /api/v1/ HTTP/1.1" 500 79746
/home/pouria/tutorial/login/login/settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 07:12:31
Django version 3.1, using settings 'login.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[23/Aug/2020 07:12:47] "GET /api/v1/ HTTP/1.1" 200 13791
[23/Aug/2020 07:12:47] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[23/Aug/2020 07:12:47] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[23/Aug/2020 07:12:47] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 200 88145
[23/Aug/2020 07:12:47] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[23/Aug/2020 07:12:47] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[23/Aug/2020 07:12:47] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[23/Aug/2020 07:13:26] "GET /api/v1/1 HTTP/1.1" 301 0
[23/Aug/2020 07:13:26] "GET /api/v1/1/ HTTP/1.1" 200 14648
[23/Aug/2020 07:13:45] "GET /api/v1/ HTTP/1.1" 200 13791
^C(venv) pouria@ubuntu:~/tutorial/login$ pip install django-rest-auth
Collecting django-rest-auth
  Downloading django-rest-auth-0.9.5.tar.gz (53 kB)
     |████████████████████████████████| 53 kB 102 kB/s 
Requirement already satisfied: Django>=1.8.0 in /home/pouria/tutorial/venv/lib/python3.8/site-packages (from django-rest-auth) (3.1)
Requirement already satisfied: djangorestframework>=3.1.3 in /home/pouria/tutorial/venv/lib/python3.8/site-packages (from django-rest-auth) (3.11.1)
Collecting six>=1.9.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: sqlparse>=0.2.2 in /home/pouria/tutorial/venv/lib/python3.8/site-packages (from Django>=1.8.0->django-rest-auth) (0.3.1)
Requirement already satisfied: asgiref~=3.2.10 in /home/pouria/tutorial/venv/lib/python3.8/site-packages (from Django>=1.8.0->django-rest-auth) (3.2.10)
Requirement already satisfied: pytz in /home/pouria/tutorial/venv/lib/python3.8/site-packages (from Django>=1.8.0->django-rest-auth) (2020.1)
Building wheels for collected packages: django-rest-auth
  Building wheel for django-rest-auth (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pouria/tutorial/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1fdetqks/django-rest-auth/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1fdetqks/django-rest-auth/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6l4mpzyz
       cwd: /tmp/pip-install-1fdetqks/django-rest-auth/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for django-rest-auth
  Running setup.py clean for django-rest-auth
Failed to build django-rest-auth
Installing collected packages: six, django-rest-auth
    Running setup.py install for django-rest-auth ... done
Successfully installed django-rest-auth-0.9.5 six-1.15.0
(venv) pouria@ubuntu:~/tutorial/login$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 2 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): authtoken.
Run 'python manage.py migrate' to apply them.
August 23, 2020 - 07:17:13
Django version 3.1, using settings 'login.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
^C(venv) pouria@ubuntu:~/tutorial/login$ python manage.py makemigrations
No changes detected
(venv) pouria@ubuntu:~/tutorial/login$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, sessions, todos
Running migrations:
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
(venv) pouria@ubuntu:~/tutorial/login$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 07:17:30
Django version 3.1, using settings 'login.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[23/Aug/2020 07:17:34] "GET /api/v1/ HTTP/1.1" 200 13791
[23/Aug/2020 07:17:34] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[23/Aug/2020 07:17:34] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[23/Aug/2020 07:17:34] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[23/Aug/2020 07:17:34] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[23/Aug/2020 07:17:34] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[23/Aug/2020 07:17:34] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
Not Found: /api/v1/login
[23/Aug/2020 07:17:41] "GET /api/v1/login HTTP/1.1" 404 2461
Not Found: /api/v1/login/
[23/Aug/2020 07:17:44] "GET /api/v1/login/ HTTP/1.1" 404 2464
Method Not Allowed: /api/v1/rest-auth/login/
[23/Aug/2020 07:18:05] "GET /api/v1/rest-auth/login/ HTTP/1.1" 405 12611
Not Found: /api/v1/rest-auth/
[23/Aug/2020 07:18:25] "GET /api/v1/rest-auth/ HTTP/1.1" 404 3820
[23/Aug/2020 07:18:31] "GET /api/v1/rest-auth/login HTTP/1.1" 301 0
Method Not Allowed: /api/v1/rest-auth/login/
[23/Aug/2020 07:18:31] "GET /api/v1/rest-auth/login/ HTTP/1.1" 405 12611
[23/Aug/2020 07:19:26] "POST /api/v1/rest-auth/login/ HTTP/1.1" 200 12141
[23/Aug/2020 07:20:51] "GET /api/v1/rest-auth/logout HTTP/1.1" 301 0
Method Not Allowed: /api/v1/rest-auth/logout/
[23/Aug/2020 07:20:52] "GET /api/v1/rest-auth/logout/ HTTP/1.1" 405 11629
[23/Aug/2020 07:21:10] "GET /admin/ HTTP/1.1" 200 5741
[23/Aug/2020 07:21:15] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[23/Aug/2020 07:21:15] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 1789
[23/Aug/2020 07:21:15] "GET /static/admin/css/base.css HTTP/1.1" 200 16307
[23/Aug/2020 07:21:15] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[23/Aug/2020 07:21:15] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[23/Aug/2020 07:21:15] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[23/Aug/2020 07:21:16] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[23/Aug/2020 07:21:16] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[23/Aug/2020 07:21:16] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[23/Aug/2020 07:21:16] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[23/Aug/2020 07:21:16] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[23/Aug/2020 07:21:21] "GET /admin/logout/ HTTP/1.1" 200 1509
[23/Aug/2020 07:22:00] "GET /api/v1/ HTTP/1.1" 200 13756
[23/Aug/2020 07:22:00] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[23/Aug/2020 07:22:00] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[23/Aug/2020 07:22:00] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41992)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /favicon.ico
[23/Aug/2020 07:22:11] "GET /api/v1/1/ HTTP/1.1" 200 14613
[23/Aug/2020 07:22:21] "PUT /api/v1/1/ HTTP/1.1" 200 14616
[23/Aug/2020 07:22:27] "PUT /api/v1/1/ HTTP/1.1" 200 14613
Not Found: /api/v1/1/rest-auth/login
[23/Aug/2020 07:22:46] "GET /api/v1/1/rest-auth/login HTTP/1.1" 404 2497
Not Found: /api/v1/1/rest/auth/login
[23/Aug/2020 07:22:52] "GET /api/v1/1/rest/auth/login HTTP/1.1" 404 2497
Method Not Allowed: /api/v1/rest-auth/login/
[23/Aug/2020 07:23:14] "GET /api/v1/rest-auth/login/ HTTP/1.1" 405 12576
[23/Aug/2020 07:23:14] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[23/Aug/2020 07:23:15] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[23/Aug/2020 07:23:15] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[23/Aug/2020 07:23:15] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[23/Aug/2020 07:23:15] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[23/Aug/2020 07:23:15] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[23/Aug/2020 07:23:26] "POST /api/v1/rest-auth/login/ HTTP/1.1" 200 12141
^C^C
(venv) pouria@ubuntu:~/tutorial/login$ cd ..
(venv) pouria@ubuntu:~/tutorial$ cd 2
(venv) pouria@ubuntu:~/tutorial/2$ cd tutorial
(venv) pouria@ubuntu:~/tutorial/2/tutorial$ python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/pouria/tutorial/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
^C(venv) pouria@ubuntu:~/tutorial/2/tutorial$ deativate
^[[Bdeativate: command not found
(venv) pouria@ubuntu:~/tutorial/2/tutorial$ deativate
deativate: command not found
(venv) pouria@ubuntu:~/tutorial/2/tutorial$ deactivate
pouria@ubuntu:~/tutorial/2/tutorial$ source ~/cascade/env/bin/activate
(env) pouria@ubuntu:~/tutorial/2/tutorial$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 08:01:35
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
/home/pouria/tutorial/2/tutorial/snippets/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 08:22:16
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
/home/pouria/tutorial/2/tutorial/snippets/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 08:22:54
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:23:03] "GET / HTTP/1.1" 200 9993
[23/Aug/2020 08:23:03] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[23/Aug/2020 08:23:03] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[23/Aug/2020 08:23:03] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[23/Aug/2020 08:23:03] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[23/Aug/2020 08:23:03] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[23/Aug/2020 08:23:03] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
******************* Call method works :) ******************
Not Found: /favicon.ico
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:23:09] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
Not Found: /accounts/login/
[23/Aug/2020 08:23:09] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 404 5762
******************* Call method works :) ******************
login
[23/Aug/2020 08:23:14] "GET /api-auth/login/?next=/ HTTP/1.1" 200 2701
******************* Call method works :) ******************
login
[23/Aug/2020 08:23:17] "POST /api-auth/login/ HTTP/1.1" 302 0
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:23:17] "GET / HTTP/1.1" 200 10222
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:23:20] "GET /snippets/ HTTP/1.1" 200 59559
******************* Call method works :) ******************
logout
[23/Aug/2020 08:23:28] "GET /api-auth/logout/?next=/snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:23:28] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
Not Found: /accounts/login/
[23/Aug/2020 08:23:28] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 404 5762
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:23:36] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:23:40] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
Not Found: /accounts/login/
[23/Aug/2020 08:23:40] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 404 5762
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:24:29] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
login
[23/Aug/2020 08:24:32] "GET /api-auth/login/?next=/ HTTP/1.1" 200 2701
/home/pouria/tutorial/2/tutorial/snippets/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 08:25:19
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:25:24] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:25:27] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
Not Found: /accounts/login/
[23/Aug/2020 08:25:27] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 404 5762
/home/pouria/tutorial/2/tutorial/snippets/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 08:26:06
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:26:11] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:26:13] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
Not Found: /accounts/login/
[23/Aug/2020 08:26:13] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 404 5762
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:26:19] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
login
[23/Aug/2020 08:26:20] "GET /api-auth/login/?next=/ HTTP/1.1" 200 2701
/home/pouria/tutorial/2/tutorial/snippets/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 08:26:42
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:26:52] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:26:55] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
Not Found: /accounts/login/
[23/Aug/2020 08:26:55] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 404 5762
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 08:28:13
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:28:20] "GET / HTTP/1.1" 200 9999
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:28:23] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
Not Found: /accounts/login/
[23/Aug/2020 08:28:23] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 404 6070
******************* Call method works :) ******************
Not Found: /accounts/login/
[23/Aug/2020 08:28:38] "GET /accounts/login/ HTTP/1.1" 404 6054
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:28:46] "GET / HTTP/1.1" 200 9999
******************* Call method works :) ******************
login
[23/Aug/2020 08:28:48] "GET /accounts/login/login/?next=/ HTTP/1.1" 200 2707
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 08:29:07
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:29:13] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:29:16] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 08:29:16] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 200 2710
******************* Call method works :) ******************
login
[23/Aug/2020 08:29:24] "POST /accounts/login/ HTTP/1.1" 302 0
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:29:24] "GET /snippets/ HTTP/1.1" 200 59559
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:37:57] "GET / HTTP/1.1" 200 10222
[23/Aug/2020 08:37:57] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[23/Aug/2020 08:37:57] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[23/Aug/2020 08:37:57] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[23/Aug/2020 08:37:57] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[23/Aug/2020 08:37:57] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[23/Aug/2020 08:37:57] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
******************* Call method works :) ******************
user-list
/home/pouria/cascade/env/lib/python3.8/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'django.contrib.auth.models.User'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[23/Aug/2020 08:37:59] "GET /users/ HTTP/1.1" 200 10926
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:38:04] "GET / HTTP/1.1" 200 10222
******************* Call method works :) ******************
change password-list
Method Not Allowed: /change password/
[23/Aug/2020 08:38:05] "GET /change%20password/ HTTP/1.1" 405 12451
******************* Call method works :) ******************
logout
[23/Aug/2020 08:38:10] "GET /accounts/logout/?next=/change%20password/ HTTP/1.1" 302 0
******************* Call method works :) ******************
change password-list
[23/Aug/2020 08:38:10] "GET /change%20password/ HTTP/1.1" 302 0
******************* Call method works :) ******************
Not Found: /api-auth/login/
[23/Aug/2020 08:38:10] "GET /api-auth/login/?next=/change%2520password/ HTTP/1.1" 404 5773
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 08:40:16
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:40:23] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:40:26] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 08:40:26] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 200 2710
******************* Call method works :) ******************
login
[23/Aug/2020 08:40:29] "POST /accounts/login/ HTTP/1.1" 302 0
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:40:29] "GET /snippets/ HTTP/1.1" 200 59559
******************* Call method works :) ******************
logout
[23/Aug/2020 08:40:32] "GET /accounts/logout/?next=/snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:40:32] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 08:40:32] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 200 2710
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:40:47] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:40:51] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 08:40:51] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 200 2710
******************* Call method works :) ******************
login
[23/Aug/2020 08:40:55] "POST /accounts/login/ HTTP/1.1" 302 0
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:40:55] "GET /snippets/ HTTP/1.1" 200 59559
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:40:58] "GET / HTTP/1.1" 200 10222
******************* Call method works :) ******************
change password-list
Method Not Allowed: /change password/
[23/Aug/2020 08:41:00] "GET /change%20password/ HTTP/1.1" 405 12451
******************* Call method works :) ******************
logout
[23/Aug/2020 08:41:03] "GET /accounts/logout/?next=/change%20password/ HTTP/1.1" 302 0
******************* Call method works :) ******************
change password-list
[23/Aug/2020 08:41:03] "GET /change%20password/ HTTP/1.1" 302 0
******************* Call method works :) ******************
Not Found: /api-auth/login/
[23/Aug/2020 08:41:03] "GET /api-auth/login/?next=/change%2520password/ HTTP/1.1" 404 5935
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:41:11] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
user-list
[23/Aug/2020 08:41:13] "GET /users/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 08:41:13] "GET /accounts/login/?next=/users/ HTTP/1.1" 200 2707
******************* Call method works :) ******************
login
[23/Aug/2020 08:41:16] "POST /accounts/login/ HTTP/1.1" 302 0
******************* Call method works :) ******************
user-list
/home/pouria/cascade/env/lib/python3.8/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'django.contrib.auth.models.User'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[23/Aug/2020 08:41:16] "GET /users/ HTTP/1.1" 200 10926
******************* Call method works :) ******************
logout
[23/Aug/2020 08:41:22] "GET /accounts/logout/?next=/users/ HTTP/1.1" 302 0
******************* Call method works :) ******************
user-list
[23/Aug/2020 08:41:23] "GET /users/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 08:41:23] "GET /accounts/login/?next=/users/ HTTP/1.1" 200 2707
******************* Call method works :) ******************
logout
[23/Aug/2020 08:41:36] "GET /accounts/logout/?next=/users/ HTTP/1.1" 302 0
******************* Call method works :) ******************
user-list
[23/Aug/2020 08:41:36] "GET /users/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 08:41:37] "GET /accounts/login/?next=/users/ HTTP/1.1" 200 2707
******************* Call method works :) ******************
login
[23/Aug/2020 08:41:40] "GET /accounts/login/?next=/users/ HTTP/1.1" 200 2707
******************* Call method works :) ******************
change password-list
[23/Aug/2020 08:41:44] "GET /change%20password/ HTTP/1.1" 302 0
******************* Call method works :) ******************
Not Found: /api-auth/login/
[23/Aug/2020 08:41:44] "GET /api-auth/login/?next=/change%2520password/ HTTP/1.1" 404 5935
/home/pouria/tutorial/2/tutorial/snippets/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 08:44:44
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:44:48] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:44:50] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 08:44:50] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 200 2710
******************* Call method works :) ******************
change password-list
[23/Aug/2020 08:44:53] "GET /change%20password/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 08:44:53] "GET /accounts/login/?next=/change%2520password/ HTTP/1.1" 200 2719
******************* Call method works :) ******************
login
[23/Aug/2020 08:44:56] "POST /accounts/login/ HTTP/1.1" 302 0
******************* Call method works :) ******************
change password-list
Method Not Allowed: /change password/
[23/Aug/2020 08:44:56] "GET /change%20password/ HTTP/1.1" 405 12451
******************* Call method works :) ******************
logout
[23/Aug/2020 08:44:59] "GET /accounts/logout/?next=/change%20password/ HTTP/1.1" 302 0
******************* Call method works :) ******************
change password-list
[23/Aug/2020 08:44:59] "GET /change%20password/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 08:44:59] "GET /accounts/login/?next=/change%2520password/ HTTP/1.1" 200 2719
******************* Call method works :) ******************
login
[23/Aug/2020 08:45:12] "POST /accounts/login/ HTTP/1.1" 302 0
******************* Call method works :) ******************
change password-list
Method Not Allowed: /change password/
[23/Aug/2020 08:45:12] "GET /change%20password/ HTTP/1.1" 405 12451
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:45:23] "GET / HTTP/1.1" 200 10222
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/tutorial/urls.py", line 28, in <module>
    path('', include('snippets.urls')),
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/snippets/urls.py", line 115, in <module>
    path('', login_required(include(router.urls))),
NameError: name 'login_required' is not defined
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 08:47:09
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
None
Internal Server Error: /
Traceback (most recent call last):
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: 'tuple' object is not callable
[23/Aug/2020 08:47:13] "GET / HTTP/1.1" 500 66437
******************* Call method works :) ******************
None
Internal Server Error: /
Traceback (most recent call last):
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: 'tuple' object is not callable
[23/Aug/2020 08:48:17] "GET / HTTP/1.1" 500 66300
******************* Call method works :) ******************
None
Internal Server Error: /
Traceback (most recent call last):
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: 'tuple' object is not callable
[23/Aug/2020 08:48:23] "GET / HTTP/1.1" 500 66138
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 08:48:53
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:48:59] "GET / HTTP/1.1" 200 10222
[23/Aug/2020 08:48:59] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[23/Aug/2020 08:48:59] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[23/Aug/2020 08:48:59] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[23/Aug/2020 08:48:59] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[23/Aug/2020 08:48:59] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[23/Aug/2020 08:48:59] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
******************* Call method works :) ******************
logout
[23/Aug/2020 08:49:04] "GET /accounts/logout/?next=/ HTTP/1.1" 302 0
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:49:04] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:49:08] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 08:49:08] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 200 2710
******************* Call method works :) ******************
login
[23/Aug/2020 08:49:17] "POST /accounts/login/ HTTP/1.1" 302 0
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 08:49:17] "GET /snippets/ HTTP/1.1" 200 59559
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:49:20] "GET / HTTP/1.1" 200 10222
******************* Call method works :) ******************
logout
[23/Aug/2020 08:49:22] "GET /accounts/logout/?next=/ HTTP/1.1" 302 0
******************* Call method works :) ******************
api-root
[23/Aug/2020 08:49:22] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
user-list
[23/Aug/2020 08:49:54] "GET /users/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 08:49:54] "GET /accounts/login/?next=/users/ HTTP/1.1" 200 2707
******************* Call method works :) ******************
login
[23/Aug/2020 08:49:56] "POST /accounts/login/ HTTP/1.1" 302 0
******************* Call method works :) ******************
user-list
/home/pouria/cascade/env/lib/python3.8/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'django.contrib.auth.models.User'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[23/Aug/2020 08:49:56] "GET /users/ HTTP/1.1" 200 10926
******************* Call method works :) ******************
logout
[23/Aug/2020 08:50:02] "GET /accounts/logout/?next=/users/ HTTP/1.1" 302 0
******************* Call method works :) ******************
user-list
[23/Aug/2020 08:50:02] "GET /users/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 08:50:02] "GET /accounts/login/?next=/users/ HTTP/1.1" 200 2707
^C(env) pouria@ubuntu:~/tutorial/2/tutorial$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 11:56:49
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 11:56:58] "GET / HTTP/1.1" 200 9993
[23/Aug/2020 11:56:59] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[23/Aug/2020 11:56:59] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[23/Aug/2020 11:56:59] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[23/Aug/2020 11:56:59] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[23/Aug/2020 11:56:59] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[23/Aug/2020 11:56:59] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
******************* Call method works :) ******************
user-list
[23/Aug/2020 11:57:02] "GET /users/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 11:57:02] "GET /accounts/login/?next=/users/ HTTP/1.1" 200 2707
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 11:57:12] "GET /snippets/ HTTP/1.1" 200 59330
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/tutorial/urls.py", line 28, in <module>
    path('', include('snippets.urls')),
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/snippets/urls.py", line 115, in <module>
    path('accounts/logout', include(router.urls) ),
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/rest_framework/routers.py", line 78, in urls
    self._urls = self.get_urls()
  File "/home/pouria/tutorial/2/tutorial/snippets/urls.py", line 73, in get_urls
    if issubclass(viewset, viewsets.ViewSetMixin):
TypeError: issubclass() arg 1 must be a class
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/tutorial/urls.py", line 28, in <module>
    path('', include('snippets.urls')),
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/snippets/urls.py", line 106, in <module>
    router.register(r'snippets', login_required(views.SnippetViewSet.as_view()))
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/rest_framework/viewsets.py", line 74, in as_view
    raise TypeError("The `actions` argument must be provided when "
TypeError: The `actions` argument must be provided when calling `.as_view()` on a ViewSet. For example `.as_view({'get': 'list'})`
^C(env) pouria@ubuntu:~/tutorial/2/tutorial$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/tutorial/urls.py", line 28, in <module>
    path('', include('snippets.urls')),
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/snippets/urls.py", line 106, in <module>
    router.register(r'snippets', login_required(snippet_list))
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/rest_framework/routers.py", line 55, in register
    basename = self.get_default_basename(viewset)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/rest_framework/routers.py", line 138, in get_default_basename
    assert queryset is not None, '`basename` argument not specified, and could ' \
AssertionError: `basename` argument not specified, and could not automatically determine the name from the viewset, as it does not have a `.queryset` attribute.
^C(env) pouria@ubuntu:~/tutorial/2/tutorial$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 12:06:24
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 12:06:28] "GET / HTTP/1.1" 200 9993
[23/Aug/2020 12:06:28] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[23/Aug/2020 12:06:28] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[23/Aug/2020 12:06:29] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[23/Aug/2020 12:06:29] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[23/Aug/2020 12:06:29] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[23/Aug/2020 12:06:29] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:06:40] "GET /snippets/ HTTP/1.1" 200 59330
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 12:07:36
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 12:08:05] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:08:11] "GET /snippets/ HTTP/1.1" 200 59330
******************* Call method works :) ******************
api-root
[23/Aug/2020 12:08:15] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
user-list
[23/Aug/2020 12:08:16] "GET /users/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:08:16] "GET /accounts/login/?next=/users/ HTTP/1.1" 200 2707
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:08:22] "GET /snippets/ HTTP/1.1" 200 59330
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 12:09:12
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:09:17] "GET /snippets/ HTTP/1.1" 200 59330
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 12:09:32
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
Not Found: /snippets/
[23/Aug/2020 12:09:37] "GET /snippets/ HTTP/1.1" 404 4326
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 12:10:06
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
Not Found: /snippets/
[23/Aug/2020 12:10:12] "GET /snippets/ HTTP/1.1" 404 4326
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 12:10:38
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:10:42] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:10:42] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 200 2710
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 12:11:08
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 12:11:14] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:11:16] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:11:16] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 200 2710
******************* Call method works :) ******************
user-list
[23/Aug/2020 12:11:24] "GET /users/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:11:24] "GET /accounts/login/?next=/users/ HTTP/1.1" 200 2707
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/tutorial/urls.py", line 28, in <module>
    path('', include('snippets.urls')),
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/snippets/urls.py", line 118
    path('api/change-password/', login_required(ChangePasswordView.as_view()), name='change-password'),
    ^
SyntaxError: invalid syntax
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/tutorial/urls.py", line 28, in <module>
    path('', include('snippets.urls')),
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/snippets/urls.py", line 118
    path('api/change-password/', ChangePasswordView.as_view(), name='change-password'),
    ^
SyntaxError: invalid syntax
^C(env) pouria@ubuntu:~/tutorial/2/tutorial$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/tutorial/urls.py", line 28, in <module>
    path('', include('snippets.urls')),
  File "/home/pouria/cascade/env/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pouria/tutorial/2/tutorial/snippets/urls.py", line 118
    path('api/change-password/', ChangePasswordView.as_view(), name='change-password'),
    ^
SyntaxError: invalid syntax
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 12:15:04
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
api-root
[23/Aug/2020 12:15:11] "GET / HTTP/1.1" 200 9993
[23/Aug/2020 12:15:11] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[23/Aug/2020 12:15:11] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[23/Aug/2020 12:15:11] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[23/Aug/2020 12:15:11] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[23/Aug/2020 12:15:11] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[23/Aug/2020 12:15:11] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:15:13] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:15:13] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 200 2710
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:15:19] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:15:19] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 200 2710
******************* Call method works :) ******************
snippet-detail
[23/Aug/2020 12:15:29] "GET /snippets/1/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:15:29] "GET /accounts/login/?next=/snippets/1/ HTTP/1.1" 200 2712
******************* Call method works :) ******************
user-list
[23/Aug/2020 12:15:39] "GET /users/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:15:39] "GET /accounts/login/?next=/users/ HTTP/1.1" 200 2707
******************* Call method works :) ******************
login
[23/Aug/2020 12:15:43] "POST /accounts/login/ HTTP/1.1" 302 0
******************* Call method works :) ******************
user-list
/home/pouria/cascade/env/lib/python3.8/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'django.contrib.auth.models.User'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[23/Aug/2020 12:15:43] "GET /users/ HTTP/1.1" 200 10891
******************* Call method works :) ******************
user-detail
[23/Aug/2020 12:15:47] "GET /users/2/ HTTP/1.1" 200 10289
******************* Call method works :) ******************
user-detail
[23/Aug/2020 12:15:49] "GET /users/2/ HTTP/1.1" 200 10289
******************* Call method works :) ******************
user-detail
[23/Aug/2020 12:15:51] "GET /users/2/ HTTP/1.1" 200 10289
******************* Call method works :) ******************
api-root
[23/Aug/2020 12:15:53] "GET / HTTP/1.1" 200 10222
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:15:55] "GET /snippets/ HTTP/1.1" 200 59514
******************* Call method works :) ******************
snippet-detail
[23/Aug/2020 12:15:57] "GET /snippets/1/ HTTP/1.1" 200 60155
/home/pouria/tutorial/2/tutorial/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 12:16:46
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
******************* Call method works :) ******************
logout
[23/Aug/2020 12:16:51] "GET /accounts/logout/?next=/snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:16:52] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:16:52] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 200 2710
******************* Call method works :) ******************
api-root
[23/Aug/2020 12:16:57] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:17:00] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:17:00] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 200 2710
******************* Call method works :) ******************
Not Found: /remote/snippets
[23/Aug/2020 12:17:13] "GET /remote/snippets HTTP/1.1" 404 7029
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:17:17] "GET /remote/snippets/ HTTP/1.1" 200 59348
******************* Call method works :) ******************
login
[23/Aug/2020 12:17:27] "GET /accounts/login/?next=/remote/snippets/ HTTP/1.1" 200 2717
******************* Call method works :) ******************
login
[23/Aug/2020 12:17:30] "POST /accounts/login/ HTTP/1.1" 302 0
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:17:30] "GET /remote/snippets/ HTTP/1.1" 200 59577
******************* Call method works :) ******************
login
[23/Aug/2020 12:17:35] "GET /accounts/login/?next=/remote/snippets/ HTTP/1.1" 200 2717
******************* Call method works :) ******************
snippet-detail
[23/Aug/2020 12:17:39] "GET /snippets/1/ HTTP/1.1" 200 60155
******************* Call method works :) ******************
snippet-detail
[23/Aug/2020 12:17:49] "GET /snippets/2/ HTTP/1.1" 200 60105
******************* Call method works :) ******************
Not Found: /remote/snippets/1
[23/Aug/2020 12:18:06] "GET /remote/snippets/1 HTTP/1.1" 404 7035
******************* Call method works :) ******************
login
[23/Aug/2020 12:18:10] "GET /accounts/login/?next=/remote/snippets/ HTTP/1.1" 200 2717
******************* Call method works :) ******************
login
[23/Aug/2020 12:18:12] "POST /accounts/login/ HTTP/1.1" 302 0
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:18:12] "GET /remote/snippets/ HTTP/1.1" 200 59577
******************* Call method works :) ******************
Not Found: /remote/snippets/1
[23/Aug/2020 12:18:15] "GET /remote/snippets/1 HTTP/1.1" 404 7035
******************* Call method works :) ******************
snippet-detail
[23/Aug/2020 12:18:21] "GET /snippets/1/ HTTP/1.1" 200 60155
******************* Call method works :) ******************
login
[23/Aug/2020 12:18:26] "GET /accounts/login/?next=/remote/snippets/ HTTP/1.1" 200 2717
******************* Call method works :) ******************
Not Found: /remote/snippets/1/
[23/Aug/2020 12:18:33] "GET /remote/snippets/1/ HTTP/1.1" 404 7038
******************* Call method works :) ******************
snippet-detail
[23/Aug/2020 12:18:42] "GET /snippets/1/ HTTP/1.1" 200 60155
******************* Call method works :) ******************
api-root
[23/Aug/2020 12:24:33] "GET / HTTP/1.1" 200 10222
******************* Call method works :) ******************
logout
[23/Aug/2020 12:24:37] "GET /accounts/logout/?next=/ HTTP/1.1" 302 0
******************* Call method works :) ******************
api-root
[23/Aug/2020 12:24:37] "GET / HTTP/1.1" 200 9993
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:24:40] "GET /snippets/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:24:40] "GET /accounts/login/?next=/snippets/ HTTP/1.1" 200 2710
******************* Call method works :) ******************
user-list
[23/Aug/2020 12:24:47] "GET /users/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:24:47] "GET /accounts/login/?next=/users/ HTTP/1.1" 200 2707
******************* Call method works :) ******************
snippet-list
[23/Aug/2020 12:24:58] "GET /remote/snippets/ HTTP/1.1" 200 59348
******************* Call method works :) ******************
snippet-detail
[23/Aug/2020 12:25:23] "GET /snippets/1/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:25:23] "GET /accounts/login/?next=/snippets/1/ HTTP/1.1" 200 2712
******************* Call method works :) ******************
snippet-detail
[23/Aug/2020 12:25:40] "GET /snippets/1/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:25:40] "GET /accounts/login/?next=/snippets/1/ HTTP/1.1" 200 2712
******************* Call method works :) ******************
snippet-detail
[23/Aug/2020 12:25:52] "GET /snippets/1/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:25:52] "GET /accounts/login/?next=/snippets/1/ HTTP/1.1" 200 2712
******************* Call method works :) ******************
snippet-detail
[23/Aug/2020 12:26:07] "GET /snippets/1/ HTTP/1.1" 302 0
******************* Call method works :) ******************
login
[23/Aug/2020 12:26:07] "GET /accounts/login/?next=/snippets/1/ HTTP/1.1" 200 2712
/home/pouria/tutorial/2/tutorial/snippets/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 23, 2020 - 14:01:45
Django version 3.1, using settings 'tutorial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
****************** My first Middleware ********************
^C
(env) pouria@ubuntu:~/tutorial/2/tutorial$ 
(env) pouria@ubuntu:~/tutorial/2/tutorial$ ^C
(env) pouria@ubuntu:~/tutorial/2/tutorial$ 

